name: Compile with Java 8, 11, and 17 using Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t calculator-multijava .

    - name: Run container and extract compiled files
      run: |
        docker create --name temp_calc calculator-multijava
        docker cp temp_calc:/build ./compiled
        docker rm temp_calc

    - name: List compiled outputs
      run: ls -R compiled

